#!/usr/bin/env ruby
# frozen_string_literal: true

# Runnable both as an installed gem and straight from a clone.
lib = File.expand_path("../lib", __dir__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)

require "lupa"

exit Lupa::CLI.new(ARGV).run
